config/routes.rb
GeneralThingsV2::Application.routes.draw do
  resources :users

  get 'sandwiches/order'

  resources :sandwiches                                                  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  root :to => 'users#new'

end

app/models/sandwich.rb
class Sandwich < ActiveRecord::Base
  belongs_to :type
  belongs_to :user
  attr_accessible :type_id, :user_id

  def type_name
    self.type.name
  end
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_one :sandwich
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sandwiches
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
  before_filter :must_be_logged_in, :only => [:create, :order]
  
  def order
    @sandwich = Sandwich.new 
    respond_to do |format|
      format.html # order.html.erb
      format.json { render json: @sandwich }
    end
  end

  def show
    @sandwich = Sandwich.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sandwich}
    end
  end

  def index
    @sandwiches = current_user.sandwiches
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sandwich}
    end
  end

  def create
    @sandwich = Sandwich.new(params[:sandwich])
    respond_to do |format|
      if @sandwich.save
        Emailer.order_email(@sandwich, current_user).deliver
        format.html { redirect_to @sandwich, notice: 'Sandwich was successfully ordered.'}
        format.json { render json: @sandwich, status: :created, location: @sandwich }
      else
        format.html { render action: "new" }
        format.json { render json: @sandwich.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to sandwiches_order_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :must_be_logged_in, :only => [:new]
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome !"
      redirect_to sandwiches_order_path
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end

  def must_be_logged_in
     if signed_in?
       redirect_to sandwiches_order_path
     else
       redirect_to sessions_new_path
     end
  end

  private

    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Sandwich maker</a>
    by Junior Joanis
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Order", sandwiches_order_path %></li>
      <% else %>
         <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
     <div class="container">
         <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Sandwich maker</a>
          <div class="nav-collapse">
            <ul class="nav">
              <% if signed_in? %>
              <li class="order"><%= link_to "Order", sandwiches_order_path %></li>
              <li class="profile" ><%= link_to "Profile", current_user %></li>
              <li class="old-sandwiches"><%= link_to "My old sandwiches", sandwiches_path %></li>
              <li class="signout"><%= link_to "Sign out", signout_path, method: "delete" %></li>
              <% else %>
               <li class="signin"><%= link_to "Sign in", signin_path %></li>
             <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sandwich Maker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
  </style>
</head>
<body>

<%= render "/shared/fb_header" %>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= render "/layouts/header" %>

<div class="container">
  <%= yield %>
</div>
<%= render "/layouts/footer" %>

</body>
</html>

app/views/sandwiches/_form.html.erb
<% if signed_in? %>
<%= form_for @sandwich, :html => { :class => "well" }  do |f| %>
  <% if @sandwich.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sandwich.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @sandwich.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% type_list = Type.all.map{ |t| [t.name,t.id]} %>
    Choose your sandwich: 
    <%= select(:sandwich, :type_id, options_for_select(type_list)) %>
    <%= hidden_field_tag "sandwich[user_id]", current_user.id  %>
  </div>
  <div class="actions">
    <%= f.submit  "Order sandwich" %>
  </div>
<% end %>

<% else %>
 <p> Please <%= link_to "Sign in", signin_path %></p>
<% end %>

app/views/sandwiches/index.html.erb
<h1>My Last sandwiches</h1>

<table class="table table-striped" >
<% @sandwiches.each do |sandwich| %>
   <tr> 
     <td><%= sandwich.type_name %> </td>
     <td> Ordered on : <%=  sandwich.created_at.strftime("%A %d %Y ")%> </td>
   </tr>
<% end %>
</table>

app/views/sandwiches/order.html.erb
<h1>Order your Sandwich</h1>
<p>Try the best sandwiches...</p>


<%= render 'form' %>

app/views/sandwiches/show.html.erb
<h1>Sandwiches Details: </h1>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sandwich.type_name %>
</p>


<%= render "shared/twitter" , :url => sandwiches_path, :text => "I just ordered an sandwich #{@sandwich.type_name }" %>
<%= render "shared/facebook", :url => sandwiches_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_facebook.html.erb
<div class="fb-like" data-href="<%= url %>" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true"></div>

app/views/shared/_fb_header.html.erb
<script type="text/javascript" >
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=237579242980490";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

app/views/shared/_twitter.html.erb
<a href="https://twitter.com/share?url=<%= url %>&text=<%= text %>" class="twitter-share-button" data-lang="en">Tweet</a>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, :html => { :class => "well" } do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <br/> 
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1> Profile: </h1>

<p> <strong> Name: </strong> <%= @user.name %> </p>
<p> <strong> Email: </strong> <%= @user.email %></p>